/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ShortAnswerWizPage.java
 *
 * Created on Jun 24, 2011, 1:29:37 AM
 */
package lk.floss.moe.mqe.ui;

import java.util.ArrayList;
import lk.floss.moe.mqe.font.SinhalaFontResource;

/**
 *
 * @author sam
 */
public class ShortAnswerWizPage extends javax.swing.JPanel {
    
    
    ArrayList<ShortAnswerPanel> answerPanels = new ArrayList<ShortAnswerPanel> ();

    /** Creates new form ShortAnswerWizPage */
    public ShortAnswerWizPage() {
        initComponents();
        initAnswerPanels();
    }
    
    
    private void initAnswerPanels() {
        for(int i = 0; i<8; i++) {
            answerPanels.add(new ShortAnswerPanel());
        }
        
        for (ShortAnswerPanel shortAnswerPanel : answerPanels) {
            answersInnerPanel.add(shortAnswerPanel);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        questionNameField = new javax.swing.JTextField();
        answersPanel = new javax.swing.JScrollPane();
        answersInnerPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        questionTextPane = new javax.swing.JTextArea();

        jLabel1.setText("Question Name");

        jLabel2.setText("Question Text");

        questionNameField.setFont(SinhalaFontResource.getBhashita(12));

        answersInnerPanel.setLayout(new javax.swing.BoxLayout(answersInnerPanel, javax.swing.BoxLayout.Y_AXIS));
        answersPanel.setViewportView(answersInnerPanel);

        questionTextPane.setColumns(20);
        questionTextPane.setRows(5);
        jScrollPane1.setViewportView(questionTextPane);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(answersPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 572, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 446, Short.MAX_VALUE)
                            .addComponent(questionNameField, javax.swing.GroupLayout.DEFAULT_SIZE, 446, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(questionNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(answersPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel answersInnerPanel;
    private javax.swing.JScrollPane answersPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    protected javax.swing.JTextField questionNameField;
    protected javax.swing.JTextArea questionTextPane;
    // End of variables declaration//GEN-END:variables
}
