/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ShortAnswerPanel.java
 *
 * Created on Jun 24, 2011, 1:36:46 AM
 */
package lk.floss.moe.mqe.ui;

import lk.floss.moe.mqe.quiz.ShortAnswerQuestion;
import lk.floss.moe.mqe.font.SinhalaFontResource;
/**
 *
 * @author sam
 */
public class ShortAnswerPanel extends javax.swing.JPanel {

    /** Creates new form ShortAnswerPanel */
    public ShortAnswerPanel() {
        initComponents();
        marksSpan.setValue(100);
        updateEnebled();
    }
    
    public final void updateEnebled() {
        if(enableCB.isSelected()) {
            answerField.setEnabled(true);
            feedbackField.setEnabled(true);
            answerLblLabel.setEnabled(true);
            feedbackLblLabel.setEnabled(true);
        } else {
            answerField.setEnabled(false);
            feedbackField.setEnabled(false);
            answerLblLabel.setEnabled(false);
            feedbackLblLabel.setEnabled(false);
        }
    }
    
    
    public void addAnswerToQuestion(ShortAnswerQuestion question) {
        if(question==null) return;
        if(!enableCB.isSelected()) return;
        question.addAnswer(answerField.getText(), feedbackField.getText(), ((Integer)marksSpan.getValue()).intValue());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        enableCB = new javax.swing.JCheckBox();
        answerLblLabel = new javax.swing.JLabel();
        answerField = new javax.swing.JTextField();
        marksSpan = new javax.swing.JSpinner();
        feedbackField = new javax.swing.JTextField();
        feedbackLblLabel = new javax.swing.JLabel();

        enableCB.setText("Enable");
        enableCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enableCBActionPerformed(evt);
            }
        });

        answerLblLabel.setText("Answer");

        answerField.setFont(SinhalaFontResource.getBhashita(12));

        feedbackField.setFont(SinhalaFontResource.getBhashita(12));

        feedbackLblLabel.setText("Feedback");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(enableCB)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(answerLblLabel)
                            .addComponent(feedbackLblLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(feedbackField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
                            .addComponent(answerField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(marksSpan, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(enableCB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(answerLblLabel)
                    .addComponent(marksSpan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(answerField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(feedbackField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(feedbackLblLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void enableCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enableCBActionPerformed
        updateEnebled();
    }//GEN-LAST:event_enableCBActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField answerField;
    private javax.swing.JLabel answerLblLabel;
    private javax.swing.JCheckBox enableCB;
    private javax.swing.JTextField feedbackField;
    private javax.swing.JLabel feedbackLblLabel;
    private javax.swing.JSpinner marksSpan;
    // End of variables declaration//GEN-END:variables
}
